[build]
  publish = "build"  # Adjust this if your build output directory is different
  command = "npm run build"  # Adjust this if your build command is different

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
